/*  SCE CONFIDENTIAL
 *  PlayStation(R)3 Programmer Tool Runtime Library 330.001
 *  Copyright (C) 2008 Sony Computer Entertainment Inc.
 *  All Rights Reserved.
 */
 
void main
(
	float4 position	: POSITION,
	float4 color	: COLOR,

	uniform float4x4 ModelViewProjMatrix : C0,

	out float4 oPosition : POSITION,
	out float4 oColor    : COLOR
)
{
	oPosition = mul(ModelViewProjMatrix, position);
	oColor = color;
}
